### ISSUE TITLE
multi-channel support

### ISSUE THREAD

**Issue by umlaeute** [asb2m10/jsusfx#11]
`jsusfx~` currently only allows for stereo i/o.
however, the underlying JSFX allows for (currently) up to 64 channels in either direction.
it would be great if this could be supported.

**Comment by umlaeute** [comment]
note: in patcher languages like Pd or Max/MSP, it's quite impossible to change the number of iolets dynamically. so a generic `[jsusfx~]` object that can load any number of effects needs to guarantee a fixed number of channels (and stereo is a safe default).

however, if an object only loads a single effect (see #6 ), the number of channels can be defined within the script.
i wonder what the best way to do that would be:

- check for the highest `spl<ID>` used in the script
- count `in_pin` and `out_pin` lines in the header.

i guess the latter is the correct approach.
this would also allow to have a different number of inlets and outlets.

however, i'm not sure whether the *language specs* allow this (e.g. there is only a single `num_ch` variable; what would it's value be? `max(num_ins, num_outs)`?)

**Comment by asb2m10** [comment]
I'm planning to do a "runtime" object that is called `jxrt~` and it is used to run one script. #6 implementation will probably use this object. `jsusfx~` should be used for development / script browsing. Otherwise, this shouldn't be a problem since the inlets/outlets are created when the script is read.

I think `in_pin` / `out_pin` should dictate the number of channels. `num_ch` is used for reference scripts that uses the `import` keyword (that is not yet supported in jsusfx) to know the number of channels on the global script. Now, the to compute the correct value of this; I'm not sure either...

**Comment by marcel303** [comment]
I made some changes in the pull request I made which,

- Counts the number of in_pin and out_pin statements in the top part of the script. So if a script uses these we can count the number of ins/outs. Some scripts omit it, but I think it's safe to assume those scripts are mono or stereo, not multi-channel ones.
- Adds numInputs and numOutputs to the DSP process(..) methods.
- Adds spl0 .. spl63 and spl(channelIndex) syntax support.

So theoretically it should be possible to support up to 64 inputs and outputs!

I have no idea how to make this happen in either Pd or Max, so from here you're on your own. :-)

**Comment by marcel303** [comment]
@umlaeute The num_ch variable is used to store the number of assigned input samples. So if a script is expecting 4 inputs, spl1-4, but the routing/bus is set to use only two channels, num_ch is set to two, and spl3 and spl4 contain garbage. The script should check for this, and handle cases where num_ch < 4 gracefully.

@umlaeute Are you sure patching languages like Max, Pd, don't allow for dynamic iolets? Max has the unpack node, which has a number of outputs set by the format string you give it. So it should be possible to change the number of outlets (and probably inlets too) based on the internal state of the node. This would allow the Max node (and possibly Pd, I don't know), to look at the numInputs and numOutput fields calculated by counting the in_pin and out_pin fields to dynamically resize the inlets/outlets.

**Comment by umlaeute** [comment]
any Pd respo Max object can determine its number of iolets at instantiation time.
however, it cannot change the number of iolets at "runtime".

Consider the `[jsusfx gain.jsfx]` loaded with stereo script, so it has 2 inlet and 2 outlets.
Now, when I send it a `[compile ambienc3o3d.jsfx(` message, it would load a new script that has 1 inlet and 16 outlets.
What is the object supposed to do? re-configure itself, disconnecting and removing the 2nd inlet, and adding 14 outlets that are not connected to anything (because how should the object know where to connect them to)??

so:
- once an object is instantiated, the number of iolets cannot change anymore
- the user could re-instantiate the object, which might change the number of iolets
- if a single `[jsusfx~]` instance can only load a single script, this is not a problem (because the script - as loaded - cannot change its input/output anymore)
- if you can load different scripts (e.g. via the `[compile(` message), possibly containing different input/output configurations, the user should have a way to set the number of inlets/outlets they want (basically, they specify the width of the input/output bus)
   - either the first script defines the number of iolets
   - or the user can specify the iolets when instantiating the object

probably something like this:
-  `[jsusfx~ bla]` loads the "bla.jsfx" script, reads the required number of inputs/outputs and creates iolets accordingly.
    - maybe this should fix the script so it cannot be changed anymore (something along the #6 idea), and the `[compile(` message is ignored.
- `[jsusfx~ 2 16]` creates a 2-input 16-output object without any script loaded (and some meaningful default behaviour, e.g. outputting silence)
   - scripts that get loaded via the `[compile(` message will always need to adhere to this n-input m-output configuration.

**Comment by marcel303** [comment]
Hi,
I researched a bit how Max instantiates nodes. I'm still new to Max externals (having never written one myself), but I see what you mean. I see now the unpack node gets reinstantiated each time one changes the format. So that explains why it works for this node.

> Consider the [jsusfx gain.jsfx] loaded with stereo script, so it has 2 inlet and 2 outlets.
> Now, when I send it a [compile ambienc3o3d.jsfx( message, it would load a new script that has 1 inlet and 16 outlets.
> What is the object supposed to do? re-configure itself, disconnecting and removing the 2nd inlet, and adding 14 outlets that are not connected to anything (because how should the object know where to connect them to)??

I added support for exactly this in my own patching system. Except the system takes care of disconnecting and (re)connecting inputs and outputs. The node just supplies lists of new (named) inputs and outputs. But Max cannot do this, which makes sense I guess, in a real-time DSP context.

I think your idea of setting the bus size when instantiating the object is a nice solution. You could do something like [jsusfx~ 4 4] and prepare it for working with any first order ambisonics script from the ATK.

From the jsusfx library point of view, the number of iolets of the node, and the number of inputs and outputs used by the script are decoupled, so it will work for any config. Just set script inputs with missing inlets to 0, and set num_ch accordingly, and output zeroes for any outlets left untouched by the script.

**Comment by asb2m10** [comment]
I have implement what @umlaeute suggested, the only difference is that the iolets are decided upon the instantiation of the object. You can compile it again, but the new pin configuration will be ignored.
