### ISSUE TITLE
build artefact in repository

### ISSUE THREAD

**Issue by umlaeute** [asb2m10/jsusfx#8]
i don't know whether this is really an issue (or by intention), but:

the file `WDL/eel2/asm-nseel-x64.obj` seems to be a build-artefact (what's that...W32/64bit?) that was accidentally checked in and should be removed.

**Comment by asb2m10** [comment]
It's the intention of the [original author](https://github.com/justinfrankel/WDL/tree/master/WDL/eel2) .. I **think** he did this because there is a lot of voodoo going on and generating those artifacts requires nasm and php... But yes, I'm for removing those and generating it from scratch even if it requires those dependencies. First I need to understand the process and why my mac x64 was able to link to work without having the dependency. 

Until this is sort out, I'll leave the 'artifact' there.

**Comment by asb2m10** [comment]
It was there because few people do have php installed with Windows, I think. This object can be generated by using a2x64.php that will translate asm-nseel-x86-gcc.c into a Windows source for nasm. I'll add that requirement in the build when the windows build we be needed.
